### ISSUE TITLE
Flashing SD - which size 

### ISSUE THREAD

**Issue by TigerClaw33** [kiteretro/Circuit-Sword-Lite#1]
Hi, is this image here for raspberry pi zero Oder zero WLAN ? An which size for SD card is recommended ?

**Comment by kiteretro** [comment]
Yes, see the ‘releases’ tab at the top here :) bare minimum is 4gb, 16gb is a good recommendation

**Comment by TigerClaw33** [comment]
Then better 32 GB ?

**Comment by kiteretro** [comment]
You can go bigger, it's up to you :) I would always say 16gb _or more_
