### ISSUE TITLE
Circuit Sword Lite v1.4A USB Hub Not Working

### ISSUE THREAD

**Issue by IronManion** [kiteretro/Circuit-Sword-Lite#13]
Mirroring the Q here just in case this is the better place :-) 

https://sudomod.com/forum/viewtopic.php?f=51&t=10458

**Comment by kiteretro** [comment]
Hi, I've replied to that thread, but here is the message also:

What software image are you using? That looks like maybe the SAIO or the Circuit Sword (NOT the Lite) one, could you make sure that you use an image from here and try again? https://github.com/kiteretro/Circuit-Sword-Lite/releases/tag/v1.0.1

**Comment by IronManion** [comment]
Thanks!  That worked!
