### ISSUE TITLE
Sword Lots USB connection 

### ISSUE THREAD

**Issue by TigerClaw33** [kiteretro/Circuit-Sword-Lite#2]
Hi,
with the sword lite there is a problem with case modification. If I cut the hole for USB it's not possible to connect a cable because the USB on  sword lite is sitting to much inside the case. With normal sword it's working fine because we have to use type C adapter and it's long enough :(

**Comment by kiteretro** [comment]
Like the ‘Super AIO’ you need to use an ‘extended’ micro usb. They are called 8mm micro usb, see if you can find one online :) I will add this to the parts list

**Comment by kiteretro** [comment]
I have added a link to the electronics page, and including it here for you, but you need the '8mm' long connector: https://www.aliexpress.com/item/8mm-Extra-Long-Micro-USB-Charging-Cable-For-Oukitel-K10000-K3-C8-Blackview-A7-A20-A30/32918770413.html
