### ISSUE TITLE
USB Flashing

### ISSUE THREAD

**Issue by TigerClaw33** [kiteretro/Circuit-Sword-Lite#3]
Hi, 
if I format a USB Stick and create folder "retropie" and put it into the kite lite USB it has no effect. Normally it has to copy the files and folders for the roms.

Update: If USB EXT switch is enabled it works fine but then sound is off :(

**Comment by kiteretro** [comment]
Have you moved the little switch in the battery bay to "EXT-USB-EN" ? https://github.com/kiteretro/Circuit-Sword-Lite/wiki/Configuration-Switch-Usage

**Comment by kiteretro** [comment]
Just saw your edit (whoops). Yes that is correct, there is not a point where you need both at the same time. So switch it to use a keyboard/move files/etc .. and then switch it back to get sound :) This is the only way I was able to keep the cost and complexity down (as there is no USB HUB on the Lite).
