### ISSUE TITLE
[Fault] LED and LCD Flickering on power-on test

### ISSUE THREAD

**Issue by rmanders** [kiteretro/Circuit-Sword-Lite#4]
I may have run into an issue during step 3.8 of the [Electronics Guide](https://github.com/kiteretro/Circuit-Sword-Lite/wiki/Circuit-Sword-Lite-Electronics-Guide). When I power on for the boot-up test, the LCD and board LED's flicker at a rate of about 2-3x per second. RetroPi starts to boot but ultimately ends up with a white screen. On the circuit board, L1 feels quite warm (not sure if that is normal).  I will try to post a video this evening.

**Troubleshooting done so far:**

- used a different LCD screen with same result
- re-flashed retro pi (tried booting in TEST mode and regular mode) with same results
- Re-seated ribbon & power cables.
- Tried booting with the Pi''s soldered USB wire both connected and disconnected to the circuit sword lite)
- continuity tested usb cable soldering for shorts (none found)
- visually inspected Pi header soldering for bridges and shorts (did not see anything obvious yet)
- Tried booting on both USB and battery power with same results

It almost seems like I introduced a short circuit somewhere since the flickering affects not just the LCD but most of the led's on the board. It's like something is draining a bunch of current in periodic intervals.

**Comment by kiteretro** [comment]
Nice and detailed :) are you running from battery, USB, or battery + USB? The chip next to the inductor, is it burning hot? (ps be careful about this, as i'm expecting that little black chip with 6x legs to be REALLY hot.. ) - which if the case, is some kind of fault with the backlight circuit on the board which is most likely not caused by you at all. If that is the case then we'll need to replace your board which will be an email to me!

**Comment by rmanders** [comment]
I've tested with USB power only and with battery power only, not with both at the same time yet. I will attempt that tonight (as well as checking if the chip next to the inductor is also hot) and post back. Thank you for your help!

**Comment by rmanders** [comment]
The same flickering does occur when both battery and USB are plugged in. You are correct in that the 6-pin chip next to L1 is quite hot. Not sure if this helps, but here is a [very poor quality video](https://media.giphy.com/media/69zIB7FExkXyvNR7Gt/giphy.gif)

**Comment by kiteretro** [comment]
Yeah, so what is happening is the chip is overheating and then cooling quite rapidly.. when it overheats it turns the output off, so that's the effect that you're seeing! For me this is pretty simple to fix; replacing that black chip!

Could you send me an email, and I'll sort out repairing/replacing for you

**Comment by tychoc** [comment]
I would like to add that I too experienced this issue while testing my board after finishing GPOI soldering. For me, it turned out to be the flux left on the contacts. I scrubbed the GPIO header pins clean with alcohol and the problem went away.

**Comment by willcalderbank** [comment]
I'm having the same problem as @rmanders. The chip next to the inductor gets so hot I can barely touch it. The screen works fine for the first few seconds when booting when the chip to cool, after it heats up the flashing occurs.

**Comment by hicrash** [comment]
hello, i have the same problem L1 it´s so HOT. and the LCD is blinking.

**Comment by kiteretro** [comment]
> hello, i have the same problem L1 it´s so HOT. and the LCD is blinking.

Have you got any acetone or alcohol to attempt cleaning that area (with it off obviously) with perhaps a brush/toothbrush or something? Same for the back of the LCD connector? As a previous comment suggests it might help to clean any flux left on the board..

If you do that and it's still the same, then please send me an email and we'll sort out repairing/replacing it

**Comment by hicrash** [comment]
Still whith the same error after cleaning.
Please send me your adress for send the PCB.
Thanks

**Comment by kiteretro** [comment]
> Still whith the same error after cleaning.
> Please send me your adress for send the PCB.
> Thanks

Could you send me an email to kite@kitesitemshop.com and I'll take it from there (email record is a lot easier to reference). Thanks :)
