### ISSUE TITLE
[Issue/Enhancement] Emulation Station not working when EXT USB is enabled

### ISSUE THREAD

**Issue by uninvitedgr** [kiteretro/Circuit-Sword-Lite#5]
Hi all, I have run into the following issue:

After setting up successfully a Gameboy Zero (via SSH), I enabled the full-size USB port in order to connect an external keyboard for input. In order to do this, I flicked the EXT_USB_EN switch to ON (while powered off) and rebooted the system. 

**Issues identified:**
1) Video splash screen did not play
2) Emulation Station loaded fine and keyboard seems to be functioning (was able to navigate using the arrow keys). When tried to load ROMs, I was left with a black-screen from which I could escape using the SELECT-START combo
3) Had issues with the RetroPie menu, after selecting any of the options (raspi-config, audio etc) I was left with a black screen which I could escape using the keyboard Escape key
4) Could not drop to the terminal using F4 - was left with a black screen which I could not escape until reboot (via the switch)

Appreciate this might have something to do with the USB sound chip. Would be keen to understand if any others have same issues.

Thanks,
Kostis

**Comment by Fonzy63** [comment]
Hi all, 

First thanks to Kite for creating a SAIO circuit like this and sorry for my bad English, I am french.

Hi Kostis, I have a part of your issue.

I am using the pre-built image.
I have nearly finished my GBZ build, but I have no sound.

-I have checked the switch used to activate the external USB.
It doesn't matter if it is on or off, If I plug a keyboard on it , the external keyboard is always working.

-When I switch on or off the GBZ, I can ear a "pop" in the Speaker.

-I have tryed to update retropie using the process discribed on Github, and it didn't work better.

-I have tryed to flash again the SD card, same issue.

-I have tryed all setups possible in emulation station, same issue to.

I an not sure, there is a problem with the USB sound chip but perhaps a problem with the switch.
It seams like Retropie doesn't find any USB sound card on the board.

If anyone have an idea... It would be great.

Thank you.
Laurent

**Comment by kiteretro** [comment]
@Fonzy63 when you run in 'tester mode' does it show a failure for the USB AUDIO?

Do you have a multimeter? Could you measure when the CSL is ON the voltage on the switch on the pin labelled "A" ? With the switch on/off what does it show?

**Comment by Fonzy63** [comment]
Hi Kite , Thank you again for this little wonder!

I have tried in testing mode, USB Audio = [Fail ]

I have only some 0.26mV on the pin Labelled "A" when switch is "on" and 0.12mv when the switch is off.

**Comment by kiteretro** [comment]
Ok, two options.. one is to return to me to fix, the other is to solder a 10k resistor as pictured:

![wire](https://user-images.githubusercontent.com/7543492/47371996-b73c4980-d6e0-11e8-8e0b-037955e79485.png)

The resistor can be anywhere from 4.7-100k, doesn't really matter! Are you able to do this? It must be a resistor, it cannot be a wire only

**Comment by Fonzy63** [comment]
Ok, I have made the mod and in testing mode it is ok!
![dsc_0168](https://user-images.githubusercontent.com/44404032/47374512-6df2f680-d6ee-11e8-88bb-afaa572429fc.JPG)

![dsc_0171](https://user-images.githubusercontent.com/44404032/47374708-e2c63080-d6ee-11e8-855e-d16ca0e4f66a.JPG)

Great it is working really well!

Thank you very very much!

How can I thank you?

**Comment by kiteretro** [comment]
@Fonzy63 Hooray that's great :) your fix is very neat! You don't need to thank me any more than you already have, however I did just get a very large ko-fi donation which looks like it was from you! All I can say is: WOW! I might have to upgrade to a complete dinner meal with that! 🎉 🎈 Thank you so much, I hope you enjoy it :)

**Comment by Fonzy63** [comment]
yes, I did not know how to thank you, so I thought it would be nice to say a thank you on ko-fi.
My GBZ is great! I do not stop playing with it anymore.
Thank you again for this!
Have a nice day! 👍
