### ISSUE TITLE
Bus Error

### ISSUE THREAD

**Issue by Reptarr117** [kiteretro/Circuit-Sword-Lite#6]
keep getting a "bus error" while i configure input settings on initial start up on my circuit sword light. checked all connections, re-formatted twice, re imaged the card. (samsung evo 32gb micro SDHC) everthing boots properly but as i configure my inputs (ABXY etc. ) it will just quit to the terminal with bus error. looked all over and i dont know what else to do. 

thanks in advance for your help,
Reptarr

**Comment by kiteretro** [comment]
Could you show a picture of your soldering on both sides of the Pi Zero?

**Comment by Reptarr117** [comment]
![0](https://user-images.githubusercontent.com/40922637/49975538-a3041400-fefb-11e8-854a-2a2ff362428e.jpg)
![0](https://user-images.githubusercontent.com/40922637/49975549-af886c80-fefb-11e8-8a84-e8f5a914eca2.jpg)
![0](https://user-images.githubusercontent.com/40922637/49975556-b6af7a80-fefb-11e8-8761-ab2a62f51915.jpg)
![0](https://user-images.githubusercontent.com/40922637/49975594-dba3ed80-fefb-11e8-9bf8-36d6f44c2d0b.jpg)
Sorry it took so long. been super busy. when i booted it up and tried again i got a segmentation fault this time.

**Comment by kiteretro** [comment]
Soldering looks alright, could you try cleaning it up a bit where the SMD pads are in the top right corner? These are to do with the SD so try and clean these up a little to make sure they're not doing anything weird!

Could you show a pic of where it shows the error? Also can you collect these log files: https://github.com/kiteretro/Circuit-Sword-Lite/wiki/Troubleshooting#collecting-the-log-file
